Add fork+xpa parallelization; parallelized 2D confidence contours
  * share/fork_xpa.sl provides an interface to parallel
    processing with fork and xpa
  * configure script and top-level makefile modified to
    build contents of extras subdirectory if present.
    This subdirectory will be used to distribute libxpa
    and the fork and slxpa modules in the isis tar file.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -725,6 +725,8 @@ ATOMDB_DIR
 ASCDS_INSTALL
 EXTRA_LIB
 EXTRA_INC
+subdirs
+BUILD_ISIS_EXTRAS
 termcap_lib
 READLINE_LIB
 READLINE_DIR
@@ -758,7 +760,7 @@ CFLAGS
 CPPFLAGS
 CPP
 XMKMF'
-
+ac_subdirs_all='extras/xpa extras/slxpa'
 
 # Initialize some variables set by options.
 ac_init_help=
@@ -1336,6 +1338,7 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-largefile     omit support for large files
   --disable-xspec_tables  Compile without XSPEC table models
+  --disable-extras        Don't install extras
   --enable-warnings       turn on GCC compiler warnings
   --enable-purify         compile with Purify
 
@@ -1362,6 +1365,7 @@ Optional Packages:
   --with-atomdb=DIR      location of spectroscopy database (ATOMDB)
   --with-djbfft=DIR      Use djbfft for pileup FFTs
                                 (from DIR/lib and DIR/include)
+  --with-slxpa           slxpa module is available
   --with-readline[=arg]  arg=DIR means use GNU readline
                                 (from DIR/lib and DIR/include)
                          arg=slang means use S-Lang readline only
@@ -12050,6 +12054,46 @@ _ACEOF
 fi
 
 
+# Check whether --with-slxpa was given.
+if test "${with_slxpa+set}" = set; then
+  withval=$with_slxpa;  jh_have_slxpa=$withval
+else
+  jh_have_slxpa=no
+fi
+
+# Check whether --enable-extras was given.
+if test "${enable_extras+set}" = set; then
+  enableval=$enable_extras;  jh_extras_enable=$enableval
+else
+  jh_extras_enable=yes
+fi
+
+BUILD_ISIS_EXTRAS=no
+if test "x$jh_have_slxpa" != "xno" ; then
+   cat >>confdefs.h <<\_ACEOF
+#define HAVE_SLXPA_MODULE 1
+_ACEOF
+
+   jh_extras_enable=no
+fi
+if test X"$jh_extras_enable" = X"yes" ; then
+   if test -d extras ; then
+     BUILD_ISIS_EXTRAS=yes
+     cat >>confdefs.h <<\_ACEOF
+#define HAVE_ISIS_EXTRAS 1
+_ACEOF
+
+     ac_configure_args="$ac_configure_args --with-slanginc=$jd_slang_include_dir --with-slanglib=$jd_slang_library_dir --with-xpainc=$CONFIG_DIR/extras/xpa --with-xpalib=$CONFIG_DIR/extras/xpa"
+     subdirs="$subdirs extras/xpa extras/slxpa"
+
+
+   else
+     echo 'No extras directory - ok.'
+   fi
+fi
+
+
+
   termcap_lib=""
   for lib in termcap ncurses curses ; do
       as_ac_Lib=`echo "ac_cv_lib_${lib}''_tgetent" | $as_tr_sh`
@@ -13666,6 +13710,8 @@ ATOMDB_DIR!$ATOMDB_DIR$ac_delim
 ASCDS_INSTALL!$ASCDS_INSTALL$ac_delim
 EXTRA_LIB!$EXTRA_LIB$ac_delim
 EXTRA_INC!$EXTRA_INC$ac_delim
+subdirs!$subdirs$ac_delim
+BUILD_ISIS_EXTRAS!$BUILD_ISIS_EXTRAS$ac_delim
 termcap_lib!$termcap_lib$ac_delim
 READLINE_LIB!$READLINE_LIB$ac_delim
 READLINE_DIR!$READLINE_DIR$ac_delim
@@ -13688,7 +13734,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 34; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 36; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -14095,6 +14141,7 @@ _ACEOF
 chmod +x $CONFIG_STATUS
 ac_clean_files=$ac_clean_files_save
 
+test -d extras && ./config.status --file=extras/Makefile:extras/Makefile.in
 
 # configure is writing to config.log, and then calls config.status.
 # config.status does its own redirection, appending to config.log.
@@ -14115,6 +14162,186 @@ if test "$no_create" != yes; then
   # Use ||, not &&, to avoid exiting from the if with $? = 1, which
   # would make configure fail if this is the last instruction.
   $ac_cs_success || { (exit 1); exit 1; }
+fi
+
+#
+# CONFIG_SUBDIRS section.
+#
+if test "$no_recursion" != yes; then
+
+  # Remove --cache-file and --srcdir arguments so they do not pile up.
+  ac_sub_configure_args=
+  ac_prev=
+  eval "set x $ac_configure_args"
+  shift
+  for ac_arg
+  do
+    if test -n "$ac_prev"; then
+      ac_prev=
+      continue
+    fi
+    case $ac_arg in
+    -cache-file | --cache-file | --cache-fil | --cache-fi \
+    | --cache-f | --cache- | --cache | --cach | --cac | --ca | --c)
+      ac_prev=cache_file ;;
+    -cache-file=* | --cache-file=* | --cache-fil=* | --cache-fi=* \
+    | --cache-f=* | --cache-=* | --cache=* | --cach=* | --cac=* | --ca=* \
+    | --c=*)
+      ;;
+    --config-cache | -C)
+      ;;
+    -srcdir | --srcdir | --srcdi | --srcd | --src | --sr)
+      ac_prev=srcdir ;;
+    -srcdir=* | --srcdir=* | --srcdi=* | --srcd=* | --src=* | --sr=*)
+      ;;
+    -prefix | --prefix | --prefi | --pref | --pre | --pr | --p)
+      ac_prev=prefix ;;
+    -prefix=* | --prefix=* | --prefi=* | --pref=* | --pre=* | --pr=* | --p=*)
+      ;;
+    *)
+      case $ac_arg in
+      *\'*) ac_arg=`echo "$ac_arg" | sed "s/'/'\\\\\\\\''/g"` ;;
+      esac
+      ac_sub_configure_args="$ac_sub_configure_args '$ac_arg'" ;;
+    esac
+  done
+
+  # Always prepend --prefix to ensure using the same prefix
+  # in subdir configurations.
+  ac_arg="--prefix=$prefix"
+  case $ac_arg in
+  *\'*) ac_arg=`echo "$ac_arg" | sed "s/'/'\\\\\\\\''/g"` ;;
+  esac
+  ac_sub_configure_args="'$ac_arg' $ac_sub_configure_args"
+
+  # Pass --silent
+  if test "$silent" = yes; then
+    ac_sub_configure_args="--silent $ac_sub_configure_args"
+  fi
+
+  ac_popdir=`pwd`
+  for ac_dir in : $subdirs; do test "x$ac_dir" = x: && continue
+
+    # Do not complain, so a configure script can configure whichever
+    # parts of a large source tree are present.
+    test -d "$srcdir/$ac_dir" || continue
+
+    ac_msg="=== configuring in $ac_dir (`pwd`/$ac_dir)"
+    echo "$as_me:$LINENO: $ac_msg" >&5
+    echo "$ac_msg" >&6
+    { as_dir="$ac_dir"
+  case $as_dir in #(
+  -*) as_dir=./$as_dir;;
+  esac
+  test -d "$as_dir" || { $as_mkdir_p && mkdir -p "$as_dir"; } || {
+    as_dirs=
+    while :; do
+      case $as_dir in #(
+      *\'*) as_qdir=`echo "$as_dir" | sed "s/'/'\\\\\\\\''/g"`;; #(
+      *) as_qdir=$as_dir;;
+      esac
+      as_dirs="'$as_qdir' $as_dirs"
+      as_dir=`$as_dirname -- "$as_dir" ||
+$as_expr X"$as_dir" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
+	 X"$as_dir" : 'X\(//\)[^/]' \| \
+	 X"$as_dir" : 'X\(//\)$' \| \
+	 X"$as_dir" : 'X\(/\)' \| . 2>/dev/null ||
+echo X"$as_dir" |
+    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{
+	    s//\1/
+	    q
+	  }
+	  /^X\(\/\/\)[^/].*/{
+	    s//\1/
+	    q
+	  }
+	  /^X\(\/\/\)$/{
+	    s//\1/
+	    q
+	  }
+	  /^X\(\/\).*/{
+	    s//\1/
+	    q
+	  }
+	  s/.*/./; q'`
+      test -d "$as_dir" && break
+    done
+    test -z "$as_dirs" || eval "mkdir $as_dirs"
+  } || test -d "$as_dir" || { { echo "$as_me:$LINENO: error: cannot create directory $as_dir" >&5
+echo "$as_me: error: cannot create directory $as_dir" >&2;}
+   { (exit 1); exit 1; }; }; }
+    ac_builddir=.
+
+case "$ac_dir" in
+.) ac_dir_suffix= ac_top_builddir_sub=. ac_top_build_prefix= ;;
+*)
+  ac_dir_suffix=/`echo "$ac_dir" | sed 's,^\.[\\/],,'`
+  # A ".." for each directory in $ac_dir_suffix.
+  ac_top_builddir_sub=`echo "$ac_dir_suffix" | sed 's,/[^\\/]*,/..,g;s,/,,'`
+  case $ac_top_builddir_sub in
+  "") ac_top_builddir_sub=. ac_top_build_prefix= ;;
+  *)  ac_top_build_prefix=$ac_top_builddir_sub/ ;;
+  esac ;;
+esac
+ac_abs_top_builddir=$ac_pwd
+ac_abs_builddir=$ac_pwd$ac_dir_suffix
+# for backward compatibility:
+ac_top_builddir=$ac_top_build_prefix
+
+case $srcdir in
+  .)  # We are building in place.
+    ac_srcdir=.
+    ac_top_srcdir=$ac_top_builddir_sub
+    ac_abs_top_srcdir=$ac_pwd ;;
+  [\\/]* | ?:[\\/]* )  # Absolute name.
+    ac_srcdir=$srcdir$ac_dir_suffix;
+    ac_top_srcdir=$srcdir
+    ac_abs_top_srcdir=$srcdir ;;
+  *) # Relative name.
+    ac_srcdir=$ac_top_build_prefix$srcdir$ac_dir_suffix
+    ac_top_srcdir=$ac_top_build_prefix$srcdir
+    ac_abs_top_srcdir=$ac_pwd/$srcdir ;;
+esac
+ac_abs_srcdir=$ac_abs_top_srcdir$ac_dir_suffix
+
+
+    cd "$ac_dir"
+
+    # Check for guested configure; otherwise get Cygnus style configure.
+    if test -f "$ac_srcdir/configure.gnu"; then
+      ac_sub_configure=$ac_srcdir/configure.gnu
+    elif test -f "$ac_srcdir/configure"; then
+      ac_sub_configure=$ac_srcdir/configure
+    elif test -f "$ac_srcdir/configure.in"; then
+      # This should be Cygnus configure.
+      ac_sub_configure=$ac_aux_dir/configure
+    else
+      { echo "$as_me:$LINENO: WARNING: no configuration information is in $ac_dir" >&5
+echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2;}
+      ac_sub_configure=
+    fi
+
+    # The recursion is here.
+    if test -n "$ac_sub_configure"; then
+      # Make the cache file name correct relative to the subdirectory.
+      case $cache_file in
+      [\\/]* | ?:[\\/]* ) ac_sub_cache_file=$cache_file ;;
+      *) # Relative name.
+	ac_sub_cache_file=$ac_top_build_prefix$cache_file ;;
+      esac
+
+      { echo "$as_me:$LINENO: running $SHELL $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_srcdir" >&5
+echo "$as_me: running $SHELL $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_srcdir" >&6;}
+      # The eval makes quoting arguments work.
+      eval "\$SHELL \"\$ac_sub_configure\" $ac_sub_configure_args \
+	   --cache-file=\"\$ac_sub_cache_file\" --srcdir=\"\$ac_srcdir\"" ||
+	{ { echo "$as_me:$LINENO: error: $ac_sub_configure failed for $ac_dir" >&5
+echo "$as_me: error: $ac_sub_configure failed for $ac_dir" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+    cd "$ac_popdir"
+  done
 fi
 
 
