Add --with-xspec-modelsonly and --with-CCfits configure options

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -710,14 +710,18 @@ MODULE_LIST
 LD_FLAGS_FOR_XSPEC
 HEADAS_DIR
 HEADAS_LIBDIR
-WITH_HEADAS
 CFITSIO_INC
 CFITSIO_LIB
+CFITSIO_LIBDIR
+CFITSIO_LIBNAME
 PGPLOT_INC
 PGPLOT_LIB
 PGPLOT_LIBDIR
 XSPEC_MODULE_LIBS
 LINK_XSPEC_STATIC
+CCFITS_LIB
+CCFITS_INC
+XSPEC_MODELSONLY
 with_xspec_version
 SLANG_LIB
 SLANG_INC
@@ -1351,6 +1355,10 @@ Optional Packages:
   --with-fclibs=libs            Provide extra Fortran libraries, e.g. "-lg2c"
   --with-headas=DIR             HEADAS install directory
   --with-xspec-static=DIR       Statically link XSPEC models from DIR=$HEADAS
+  --with-xspec-modelsonly=DIR   XSPEC modelsonly install directory
+  --with-CCfits=DIR             Use DIR/lib and DIR/include for CCfits
+  --with-CCfitslib=DIR          CCfits library in DIR
+  --with-CCfitsinc=DIR          CCfits include files in DIR
   --with-xspec-version=nn       XSPEC version 11 or 12?
   --with-pgplot=DIR             Use DIR/lib and DIR/include for pgplot
   --with-pgplotlib=DIR          pgplot library in DIR
@@ -11358,6 +11366,7 @@ MODULE_LIST="cfitsio pgplot maplib"
 SLANG_LIB=no
 CFITSIO_LIB=no
 PGPLOT_LIB=no
+CCFITS_LIB=no
 
 # reasonable pgplot default
 PGPLOT_LIBDIR=/usr/local/pgplot
@@ -11369,6 +11378,31 @@ fi
 
 ATOMDB_DIR=""
 HEADAS_DIR=""
+XSPEC_MODELSONLY=""
+
+
+  if test "X$jd_prefix" = "X"
+  then
+    jd_prefix=$ac_default_prefix
+    if test "X$prefix" != "XNONE"
+    then
+      jd_prefix="$prefix"
+    fi
+    jd_exec_prefix="$jd_prefix"
+    if test "X$exec_prefix" != "XNONE"
+    then
+      jd_exec_prefix="$exec_prefix"
+    fi
+
+            eval `sh <<EOF
+      prefix=$jd_prefix
+      exec_prefix=$jd_exec_prefix
+      libdir=$libdir
+      includedir=$includedir
+      echo jd_prefix_libdir="\$libdir" jd_prefix_incdir="\$includedir"
+EOF
+`
+  fi
 
 
   case "$host_os" in
@@ -11403,10 +11437,8 @@ echo "$as_me: error: Nonexistent HEADAS directory='$HEADAS_DIR'" >&2;}
    { (exit 1); exit 1; }; }
    fi
    HEADAS_LIBDIR="${HEADAS_DIR}/lib"
-   WITH_HEADAS="-DWITH_HEADAS"
 
    MODULE_LIST="$MODULE_LIST xspec"
-
 
 
 
@@ -11429,8 +11461,6 @@ echo "$as_me: error: Nonexistent HEADAS directory='$HEADAS_DIR'" >&2;}
   esac
   if test -f "${jh_cfitsio_library_dir}/libcfitsio.$ext" ; then
      cfitsio_libname=cfitsio
-  elif test -f "${jh_cfitsio_library_dir}/libcxccfitsio.$ext" ; then
-     cfitsio_libname=cxccfitsio
   else
      cfitsio_libfile_exists=0
      cfitsio_libname=`/bin/ls ${jh_cfitsio_library_dir}/libcfitsio*.$ext`
@@ -11444,7 +11474,11 @@ echo "$as_me: error: Nonexistent HEADAS directory='$HEADAS_DIR'" >&2;}
         echo '*** WARNING:  Cannot find cfitsio library in' "$jh_cfitsio_library_dir"
      fi
   fi
-  CFITSIO_LIB="-L${jh_cfitsio_library_dir} -l${cfitsio_libname}#"
+  CFITSIO_LIB="-L${jh_cfitsio_library_dir} -l${cfitsio_libname}"
+  CFITSIO_LIBDIR="${jh_cfitsio_library_dir}"
+  CFITSIO_LIBNAME="${cfitsio_libname}"
+
+
 
 
 
@@ -11574,9 +11608,7 @@ echo "$as_me: error: Nonexistent HEADAS directory='$HEADAS_DIR'" >&2;}
    fi
    HEADAS=$jh_use_xspec_static
    HEADAS_LIBDIR="${HEADAS}/lib"
-   WITH_HEADAS="-DWITH_HEADAS"
    XSPEC_MODULE_LIBS="-L\$(config_dir)/modules/xspec/src/objs -lxspec-module \$(XS_LIBS)"
-
 
 
 
@@ -11599,8 +11631,6 @@ echo "$as_me: error: Nonexistent HEADAS directory='$HEADAS_DIR'" >&2;}
   esac
   if test -f "${jh_cfitsio_library_dir}/libcfitsio.$ext" ; then
      cfitsio_libname=cfitsio
-  elif test -f "${jh_cfitsio_library_dir}/libcxccfitsio.$ext" ; then
-     cfitsio_libname=cxccfitsio
   else
      cfitsio_libfile_exists=0
      cfitsio_libname=`/bin/ls ${jh_cfitsio_library_dir}/libcfitsio*.$ext`
@@ -11614,7 +11644,11 @@ echo "$as_me: error: Nonexistent HEADAS directory='$HEADAS_DIR'" >&2;}
         echo '*** WARNING:  Cannot find cfitsio library in' "$jh_cfitsio_library_dir"
      fi
   fi
-  CFITSIO_LIB="-L${jh_cfitsio_library_dir} -l${cfitsio_libname}#"
+  CFITSIO_LIB="-L${jh_cfitsio_library_dir} -l${cfitsio_libname}"
+  CFITSIO_LIBDIR="${jh_cfitsio_library_dir}"
+  CFITSIO_LIBNAME="${cfitsio_libname}"
+
+
 
 
 
@@ -11719,6 +11753,332 @@ fi
 
 
 
+
+# Check whether --with-xspec-modelsonly was given.
+if test "${with_xspec_modelsonly+set}" = set; then
+  withval=$with_xspec_modelsonly; jh_use_xspec_modelsonly=$withval
+else
+  jh_use_xspec_modelsonly=no
+fi
+
+if test "x$jh_use_xspec_modelsonly" != "xno"
+then
+   HEADAS_DIR=$jh_use_xspec_modelsonly
+   if test ! -d "${HEADAS_DIR}" ; then
+      { { echo "$as_me:$LINENO: error: Nonexistent HEADAS directory='$HEADAS_DIR'" >&5
+echo "$as_me: error: Nonexistent HEADAS directory='$HEADAS_DIR'" >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+   HEADAS_LIBDIR="${HEADAS_DIR}/lib"
+
+   MODULE_LIST="$MODULE_LIST xspec"
+   XSPEC_MODELSONLY=yes
+
+
+
+
+
+
+ jd_CCfits_include_dir=""
+ jd_CCfits_library_dir=""
+ jd_with_CCfits_library=""
+
+
+# Check whether --with-CCfits was given.
+if test "${with_CCfits+set}" = set; then
+  withval=$with_CCfits; jd_with_CCfits_arg=$withval
+else
+  jd_with_CCfits_arg=unspecified
+fi
+
+
+ case "x$jd_with_CCfits_arg" in
+   xno)
+     jd_with_CCfits_library="no"
+    ;;
+   x)
+    { { echo "$as_me:$LINENO: error: --with-CCfits requires a value-- try yes or no" >&5
+echo "$as_me: error: --with-CCfits requires a value-- try yes or no" >&2;}
+   { (exit 1); exit 1; }; }
+    ;;
+   xunspecified)
+    ;;
+   xyes)
+    ;;
+   *)
+    jd_CCfits_include_dir="$jd_with_CCfits_arg"/include
+    jd_CCfits_library_dir="$jd_with_CCfits_arg"/lib
+    ;;
+ esac
+
+
+# Check whether --with-CCfitslib was given.
+if test "${with_CCfitslib+set}" = set; then
+  withval=$with_CCfitslib; jd_with_CCfitslib_arg=$withval
+else
+  jd_with_CCfitslib_arg=unspecified
+fi
+
+ case "x$jd_with_CCfitslib_arg" in
+   xunspecified)
+    ;;
+   xno)
+    ;;
+   x)
+    { { echo "$as_me:$LINENO: error: --with-CCfitslib requres a value" >&5
+echo "$as_me: error: --with-CCfitslib requres a value" >&2;}
+   { (exit 1); exit 1; }; }
+    ;;
+   *)
+    jd_CCfits_library_dir="$jd_with_CCfitslib_arg"
+    ;;
+ esac
+
+
+# Check whether --with-CCfitsinc was given.
+if test "${with_CCfitsinc+set}" = set; then
+  withval=$with_CCfitsinc; jd_with_CCfitsinc_arg=$withval
+else
+  jd_with_CCfitsinc_arg=unspecified
+fi
+
+ case "x$jd_with_CCfitsinc_arg" in
+   x)
+     { { echo "$as_me:$LINENO: error: --with-CCfitsinc requres a value" >&5
+echo "$as_me: error: --with-CCfitsinc requres a value" >&2;}
+   { (exit 1); exit 1; }; }
+     ;;
+   xunspecified)
+     ;;
+   xno)
+     ;;
+   *)
+    jd_CCfits_include_dir="$jd_with_CCfitsinc_arg"
+   ;;
+ esac
+
+  { echo "$as_me:$LINENO: checking for the CCfits library and header files CCfits/CCfits.h" >&5
+echo $ECHO_N "checking for the CCfits library and header files CCfits/CCfits.h... $ECHO_C" >&6; }
+  if test X"$jd_with_CCfits_library" != Xno
+  then
+    jd_CCfits_inc_file=CCfits/CCfits.h
+
+    if test "X$jd_CCfits_inc_file" = "X"
+    then
+       jd_CCfits_inc_file=CCfits.h
+    fi
+    if test X"$jd_CCfits_include_dir" = X
+    then
+       lib_include_dirs="\
+            $jd_prefix_incdir \
+            $jh_depdir/include \
+            $jh_depdir/pgplot \
+            /usr/local/CCfits/include \
+            /usr/local/include/CCfits \
+  	  /usr/local/include \
+  	  /usr/include/CCfits \
+  	  /usr/CCfits/include \
+  	  /usr/include \
+  	  /opt/include/CCfits \
+  	  /opt/CCfits/include \
+  	  /opt/include"
+
+       for X in $lib_include_dirs
+       do
+          if test -r "$X/$jd_CCfits_inc_file"
+	  then
+  	  jd_CCfits_include_dir="$X"
+            break
+          fi
+       done
+       if test X"$jd_CCfits_include_dir" = X
+       then
+         jd_with_CCfits_library="no"
+       fi
+    fi
+
+    if test X"$jd_CCfits_library_dir" = X
+    then
+       lib_library_dirs="\
+            $jd_prefix_libdir \
+            $jh_depdir/lib \
+            $jh_depdir/pgplot \
+            /usr/local/lib \
+            /usr/local/lib/CCfits \
+            /usr/local/CCfits/lib \
+  	  /usr/lib \
+  	  /usr/lib/CCfits \
+  	  /usr/CCfits/lib \
+  	  /opt/lib \
+  	  /opt/lib/CCfits \
+  	  /opt/CCfits/lib"
+
+       case "$host_os" in
+         *darwin* )
+	   exts="dylib so a"
+	   ;;
+	 *cygwin* )
+	   exts="dll.a so a"
+	   ;;
+	 * )
+	   exts="so a"
+       esac
+
+       found=0
+       for X in $lib_library_dirs
+       do
+         for E in $exts
+	 do
+           if test -r "$X/libCCfits.$E"
+	   then
+  	     jd_CCfits_library_dir="$X"
+	     found=1
+	     break
+           fi
+         done
+	 if test $found -eq 1
+	 then
+	   break
+	 fi
+       done
+       if test X"$jd_CCfits_library_dir" = X
+       then
+         jd_with_CCfits_library="no"
+       fi
+    fi
+  fi
+
+  if test X"$jd_CCfits_include_dir" != X -a "$jd_CCfits_library_dir" != X
+  then
+    { echo "$as_me:$LINENO: result: yes: $jd_CCfits_library_dir and $jd_CCfits_include_dir" >&5
+echo "${ECHO_T}yes: $jd_CCfits_library_dir and $jd_CCfits_include_dir" >&6; }
+    jd_with_CCfits_library="yes"
+            CCFITS_LIB=-L$jd_CCfits_library_dir
+    if test "X$jd_CCfits_library_dir" = "X/usr/lib"
+    then
+      CCFITS_LIB=""
+    else
+
+if test "X$jd_CCfits_library_dir" != "X"
+then
+  if test "X$RPATH" = "X"
+  then
+
+case "$host_os" in
+  *linux*|*solaris* )
+    if test "X$GCC" = Xyes
+    then
+      if test "X$ac_R_nospace" = "Xno"
+      then
+        RPATH="-Wl,-R,"
+      else
+        RPATH="-Wl,-R"
+      fi
+    else
+      if test "X$ac_R_nospace" = "Xno"
+      then
+        RPATH="-R "
+      else
+        RPATH="-R"
+      fi
+    fi
+  ;;
+  *osf*)
+    if test "X$GCC" = Xyes
+    then
+      RPATH="-Wl,-rpath,"
+    else
+      RPATH="-rpath "
+    fi
+  ;;
+esac
+
+    if test "X$RPATH" != "X"
+    then
+      RPATH="$RPATH$jd_CCfits_library_dir"
+    fi
+  else
+    RPATH="$RPATH:$jd_CCfits_library_dir"
+  fi
+fi
+
+    fi
+
+    CCFITS_INC=-I$jd_CCfits_include_dir
+    if test "X$jd_CCfits_include_dir" = "X/usr/include"
+    then
+      CCFITS_INC=""
+    fi
+  else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+    jd_with_CCfits_library="no"
+    CCFITS_INC=""
+    CCFITS_LIB=""
+  fi
+
+
+
+  if test "$jd_with_CCfits_library" = "no"
+  then
+    { { echo "$as_me:$LINENO: error: unable to find the CCfits library and header file $jd_CCfits_inc_file" >&5
+echo "$as_me: error: unable to find the CCfits library and header file $jd_CCfits_inc_file" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+
+
+
+
+
+
+if test "X$HEADAS_LIBDIR" != "X"
+then
+  if test "X$RPATH" = "X"
+  then
+
+case "$host_os" in
+  *linux*|*solaris* )
+    if test "X$GCC" = Xyes
+    then
+      if test "X$ac_R_nospace" = "Xno"
+      then
+        RPATH="-Wl,-R,"
+      else
+        RPATH="-Wl,-R"
+      fi
+    else
+      if test "X$ac_R_nospace" = "Xno"
+      then
+        RPATH="-R "
+      else
+        RPATH="-R"
+      fi
+    fi
+  ;;
+  *osf*)
+    if test "X$GCC" = Xyes
+    then
+      RPATH="-Wl,-rpath,"
+    else
+      RPATH="-rpath "
+    fi
+  ;;
+esac
+
+    if test "X$RPATH" != "X"
+    then
+      RPATH="$RPATH$HEADAS_LIBDIR"
+    fi
+  else
+    RPATH="$RPATH:$HEADAS_LIBDIR"
+  fi
+fi
+
+fi
+
+
   # Check whether --enable-xspec_tables was given.
 if test "${enable_xspec_tables+set}" = set; then
   enableval=$enable_xspec_tables;
@@ -11754,30 +12114,6 @@ if test "x$PGPLOT_LIB" = "xno" \
    || test "${with_pgplotlib+set}" = set \
    || test "${with_pgplotinc+set}" = set
 then
-
-  if test "X$jd_prefix" = "X"
-  then
-    jd_prefix=$ac_default_prefix
-    if test "X$prefix" != "XNONE"
-    then
-      jd_prefix="$prefix"
-    fi
-    jd_exec_prefix="$jd_prefix"
-    if test "X$exec_prefix" != "XNONE"
-    then
-      jd_exec_prefix="$exec_prefix"
-    fi
-
-            eval `sh <<EOF
-      prefix=$jd_prefix
-      exec_prefix=$jd_exec_prefix
-      libdir=$libdir
-      includedir=$includedir
-      echo jd_prefix_libdir="\$libdir" jd_prefix_incdir="\$includedir"
-EOF
-`
-  fi
-
 
 
 
@@ -12354,8 +12690,6 @@ echo "$as_me: error: unable to find the cfitsio library and header file $jd_cfit
   esac
   if test -f "${jh_cfitsio_library_dir}/libcfitsio.$ext" ; then
      cfitsio_libname=cfitsio
-  elif test -f "${jh_cfitsio_library_dir}/libcxccfitsio.$ext" ; then
-     cfitsio_libname=cxccfitsio
   else
      cfitsio_libfile_exists=0
      cfitsio_libname=`/bin/ls ${jh_cfitsio_library_dir}/libcfitsio*.$ext`
@@ -12369,7 +12703,11 @@ echo "$as_me: error: unable to find the cfitsio library and header file $jd_cfit
         echo '*** WARNING:  Cannot find cfitsio library in' "$jh_cfitsio_library_dir"
      fi
   fi
-  CFITSIO_LIB="-L${jh_cfitsio_library_dir} -l${cfitsio_libname}#"
+  CFITSIO_LIB="-L${jh_cfitsio_library_dir} -l${cfitsio_libname}"
+  CFITSIO_LIBDIR="${jh_cfitsio_library_dir}"
+  CFITSIO_LIBNAME="${cfitsio_libname}"
+
+
 
 
 fi
@@ -14261,7 +14599,7 @@ MODULE_LIST!$MODULE_LIST$ac_delim
 LD_FLAGS_FOR_XSPEC!$LD_FLAGS_FOR_XSPEC$ac_delim
 HEADAS_DIR!$HEADAS_DIR$ac_delim
 HEADAS_LIBDIR!$HEADAS_LIBDIR$ac_delim
-WITH_HEADAS!$WITH_HEADAS$ac_delim
+CFITSIO_INC!$CFITSIO_INC$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -14303,13 +14641,17 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
-CFITSIO_INC!$CFITSIO_INC$ac_delim
 CFITSIO_LIB!$CFITSIO_LIB$ac_delim
+CFITSIO_LIBDIR!$CFITSIO_LIBDIR$ac_delim
+CFITSIO_LIBNAME!$CFITSIO_LIBNAME$ac_delim
 PGPLOT_INC!$PGPLOT_INC$ac_delim
 PGPLOT_LIB!$PGPLOT_LIB$ac_delim
 PGPLOT_LIBDIR!$PGPLOT_LIBDIR$ac_delim
 XSPEC_MODULE_LIBS!$XSPEC_MODULE_LIBS$ac_delim
 LINK_XSPEC_STATIC!$LINK_XSPEC_STATIC$ac_delim
+CCFITS_LIB!$CCFITS_LIB$ac_delim
+CCFITS_INC!$CCFITS_INC$ac_delim
+XSPEC_MODELSONLY!$XSPEC_MODELSONLY$ac_delim
 with_xspec_version!$with_xspec_version$ac_delim
 SLANG_LIB!$SLANG_LIB$ac_delim
 SLANG_INC!$SLANG_INC$ac_delim
@@ -14341,7 +14683,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 36; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 40; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -14856,7 +15198,12 @@ echo ""
 if test "x$HEADAS_DIR" != "x" ; then
     echo "XSPEC module configuration:"
     echo "    --with-xspec-version = ${with_xspec_version}"
-    echo "    --with-headas = $HEADAS_DIR"
+    if test x"${XSPEC_MODELSONLY}" = xyes ; then
+       headas_arg="xspec-modelsonly"
+    else
+       headas_arg="headas"
+    fi
+    echo "    --with-${headas_arg} = $HEADAS_DIR"
     ./autoconf/compiler_check.sh "$CC" "$FC" "$HEADAS_DIR"
 else
     echo "The XSPEC module will not be compiled."
